package common;

/**
 * One enum for ALL operations in the system.
 * Client sends REQUEST_*, server replies RESPONSE_* (or ERROR).
 */
public enum OpCode {
    // ===== Common =====
    ERROR,
    INFO,

    // ===== Customer/Subscriber Main Page =====
    REQUEST_RESERVATIONS_LIST,
    RESPONSE_RESERVATIONS_LIST,

    REQUEST_CANCEL_RESERVATION,
    RESPONSE_CANCEL_RESERVATION,

    REQUEST_RECOVER_CONFIRMATION_CODE,
    RESPONSE_RECOVER_CONFIRMATION_CODE,
    
    REQUEST_MAKE_RESERVATION,
    RESPONSE_MAKE_RESERVATION,

    // Pre-check reservation availability (no email/phone prompt)
    REQUEST_CHECK_AVAILABILITY,
    RESPONSE_CHECK_AVAILABILITY,

    // Subscriber-only
    REQUEST_PROFILE_GET,
    RESPONSE_PROFILE_GET,

    REQUEST_PROFILE_UPDATE_CONTACT,
    RESPONSE_PROFILE_UPDATE_CONTACT,

    REQUEST_HISTORY_GET,
    RESPONSE_HISTORY_GET,
    
    REQUEST_LOGIN_SUBSCRIBER,
    RESPONSE_LOGIN_SUBSCRIBER,

    REQUEST_LOGIN_STAFF,
    RESPONSE_LOGIN_STAFF,

    // ===== Pay Bill Page =====
    REQUEST_BILL_GET_BY_CODE,
    RESPONSE_BILL_GET_BY_CODE,

    REQUEST_PAY_BILL,
    RESPONSE_PAY_BILL,

    // ===== Terminal Page =====
    REQUEST_TERMINAL_VALIDATE_CODE,
    RESPONSE_TERMINAL_VALIDATE_CODE,

    REQUEST_TERMINAL_CHECK_IN,
    RESPONSE_TERMINAL_CHECK_IN,

    REQUEST_TERMINAL_CHECK_OUT,
    RESPONSE_TERMINAL_CHECK_OUT,

    REQUEST_TERMINAL_NO_SHOW,
    RESPONSE_TERMINAL_NO_SHOW,
    
 // ===== Agent – Subscriber Registration =====
    REQUEST_REGISTER_CUSTOMER,
    RESPONSE_REGISTER_CUSTOMER,
    
    REQUEST_SUBSCRIBERS_LIST,
    RESPONSE_SUBSCRIBERS_LIST,
    
    REQUEST_WAITING_LIST,
    RESPONSE_WAITING_LIST,
    
    REQUEST_AGENT_RESERVATIONS_LIST,
    RESPONSE_AGENT_RESERVATIONS_LIST,

}